### ISSUE TITLE
HttpProxyServerHandle里https的代理部分是不是不太全?

### ISSUE THREAD

**Issue by QuailOurs** [monkeyWie/proxyee#1]
HttpProxyServerHandle里https的代理部分是不是不太全?

**Comment by monkeyWie** [comment]
https数据没有编解码，就是纯转发原始数据。

**Comment by weirenren** [comment]
> @QuailOurs https数据没有编解码，就是纯转发原始数据。

这块可以编解码吗，代理中打印出明文
