### ISSUE TITLE
FullRequestIntercept与FullResponseIntercept不能同时使用

### ISSUE THREAD

**Issue by louyu65** [monkeyWie/proxyee#100]
当同时定义两个拦截器的时候，FullResponseIntercept的handleResponse方法无法被调用。框架里面的pipline貌似没有迭代执行，调用了FullResponseIntercept的afterResponse之后就结束了。
另外是否能在拿到response的同时也获取到FullHttpRequest对象？

**Comment by monkeyWie** [comment]
@louyu65 用的哪个版本

**Comment by monkeyWie** [comment]
同：https://github.com/monkeyWie/proxyee/issues/102
