### ISSUE TITLE
Setting proxyConfig at runtime

### ISSUE THREAD

**Issue by smichea** [monkeyWie/proxyee#120]
In order to use another proxy, I see we can set the proxyConfig in the server before starting it.
Can we also set it at runtime, for instance in a FullRequestIntercept ?

**Comment by monkeyWie** [comment]
I think this is simple to implement, just need support set proxyConfig at pipeline and use it, for example code:
```java
pipeline.setProxyConfig()
```
I will implement it recently.

**Comment by smichea** [comment]
great, thank you

**Comment by smichea** [comment]
I think there will be a problem with HTTP pipelining, is there a way to set the proxyconfig not only in the scope of the current request but for all requests on the same socket ?

**Comment by monkeyWie** [comment]
It no problem, actually multiple requests will reuse a socket by HTTP keep-alive.
