### ISSUE TITLE
FullHttpRequest如何获取完整的正确url？

### ISSUE THREAD

**Issue by dujianchi** [monkeyWie/proxyee#130]
我拦截到请求FullHttpRequest的时候，想要获取正确的url，假设原始请求如下：
```
https://www.example.org/aaa
http://bbb.example.org/ccc
https://ddd.example.org/eee
```
我通过FullHttpRequest.url()取到了：
```
/aaa
/ccc
/eee
```
然后又通过FullHttpRequest.headers().get("Host")取到了：
```
www.example.org
bbb.example.org
ddd.example.org
```
但是这个host是不带协议的，我无法判断它实际上是https还是http，我该如何获取如下的完整url？
```
https://www.example.org/aaa
http://bbb.example.org/ccc
https://ddd.example.org/eee
```

**Comment by dujianchi** [comment]
发现
`public void handleRequest(FullHttpRequest httpRequest, HttpProxyInterceptPipeline pipeline)`
中的`HttpProxyInterceptPipeline.getRequestProto()`有是否是ssl的判断，可以直接用这个判断吗？

**Comment by monkeyWie** [comment]
@dujianchi 可以的，基本的请求信息都在`HttpProxyInterceptPipeline.getRequestProto()`里面。
