### ISSUE TITLE
首字节22为什么可以判断出是ssl握手请求

### ISSUE THREAD

**Issue by jiangnenghua** [monkeyWie/proxyee#14]
https://github.com/monkeyWie/proxyee/blob/83645089f2ccfe1dd21222846abf03fed77a1db4/src/main/java/lee/study/proxyee/handler/HttpProxyServerHandle.java#L121

**Comment by monkeyWie** [comment]
参考https://tools.ietf.org/html/rfc6101#appendix-A.1
握手规定为22 handshake(22)

**Comment by jiangnenghua** [comment]
3q
