### ISSUE TITLE
自己生成的证书问题

### ISSUE THREAD

**Issue by guoqipan** [monkeyWie/proxyee#162]
#key的生成，这样是生成RSA密钥，openssl格式，2048位强度。ca.key是密钥文件名。
openssl genrsa -out ca.key 2048

#key的转换，转换成netty支持私钥编码格式
openssl rsa -in ca.key -out ca_private.der -outform der

#crt的生成，通过-subj选项可以自定义证书的相关信息
openssl req -sha256 -new -x509 -days 365 -key ca.key -out ca.crt \
    -subj "/C=CN/ST=GD/L=SZ/O=lee/OU=study/CN=testRoot"
生成完之后把ca.crt和ca_private.der复制到项目的 src/resources/中，或者实现 HttpProxyCACertFactory 接口来自定义加载根证书和私钥

通过这些命令生成证书，也把文件移动到手机 /system/etc/security/cacerts/ 并给与644权限了，但是没法拦截https请求？什么原因呢

**Comment by monkeyWie** [comment]
先在pc上试试

**Comment by guoqipan** [comment]
pc上也不拦截https ，程序默认的证书可以拦截到https

**Comment by monkeyWie** [comment]
生成好证书之后放哪了呢

**Comment by guoqipan** [comment]
resources下

**Comment by monkeyWie** [comment]
代码设置了`handleSsl(true)`吗，还有点就是根证书安装了没有

**Comment by guoqipan** [comment]
代码设置了，根证书也安装了

**Comment by monkeyWie** [comment]
把私钥和证书上传上来我试试看

**Comment by guoqipan** [comment]
[证书.zip](https://github.com/monkeyWie/proxyee/files/6477044/default.zip)

**Comment by monkeyWie** [comment]
文档写的有问题，用这个命令转化下私钥就行了：
```
openssl pkcs8 -topk8 -nocrypt -inform PEM -outform DER -in ca.key -out ca_private.der
```

**Comment by guoqipan** [comment]
可以拦截https了但是证书不受信任，已经在chrome里导入受信任的证书了

**Comment by monkeyWie** [comment]
一定要安装在受信任的根证书颁发目录下才行

**Comment by guoqipan** [comment]
是安装在这里的

**Comment by monkeyWie** [comment]
把证书和私钥再发我试试

**Comment by guoqipan** [comment]
[证书.zip](https://github.com/monkeyWie/proxyee/files/6477413/default.zip)

**Comment by monkeyWie** [comment]
我试了下没问题啊，你看看浏览器上那个证书对不对
![image](https://user-images.githubusercontent.com/13160176/118246495-99b87080-b4d4-11eb-9239-6a00fc366e25.png)
![image](https://user-images.githubusercontent.com/13160176/118246261-52ca7b00-b4d4-11eb-9db1-9c0ff913c36a.png)

**Comment by guoqipan** [comment]
证书不对，好像直接把证书放在resources目录下有点问题，我通过caCertFactory方法设置证书可以了 ，谢谢您耐心的回复

**Comment by monkeyWie** [comment]
不客气，估计是加载到默认的证书了
