### ISSUE TITLE
根据 鉴权里的账号和密码 设置二级代理

### ISSUE THREAD

**Issue by kickDick** [monkeyWie/proxyee#168]
![123123](https://user-images.githubusercontent.com/25758570/127948965-81b800c0-5931-4ab6-8bc2-70fefd146758.png)

如图 我如果要根据 鉴权信息里的 账号和密码 来动态设置 二级代理 。 再这个地方 有什么方法可以获取到 用户名和密码么

**Comment by monkeyWie** [comment]
我提交了一个[PR](https://github.com/monkeyWie/proxyee/pull/169)，支持获取授权信息上下文了，你看看是否满足需求，参考下：https://github.com/monkeyWie/proxyee/blob/master/src/test/java/com/github/monkeywie/proxyee/AuthHttpProxyServer.java

**Comment by kickDick** [comment]
你好 。已经可以实现需求 。 还有一个问题 ， 发现如果 config.setHandleSsl(true); 不开启  https 请求是无法拿到 鉴权信息的 包括 程序 也无法走到  设置二级代理部分 

`if ("CONNECT".equalsIgnoreCase(request.method().name())) {// 建立代理握手
                    status = 2;
                    HttpResponse response = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, HttpProxyServer.SUCCESS);
                    ctx.writeAndFlush(response);
                    ctx.channel().pipeline().remove("httpCodec");
                    // fix issue #42
                    ReferenceCountUtil.release(msg);
                    return;
                }`

这里判断 后 直接 返回了  下面的并不会执行 .  这个部分 是需要自己修改吗。 

另外 可以 请您喝一杯咖啡吗 😄  太感谢您的开源了

**Comment by monkeyWie** [comment]
哈哈，不客气啊，你这个需求确实现在的实现还有问题，我考虑下怎么改吧

**Comment by kickDick** [comment]
![1627977132(1)](https://user-images.githubusercontent.com/25758570/127978700-8cca59d6-f8da-40da-b834-bc6f6dc8261a.jpg)

这个地方  https 的 请求 二级代理 好像也无效 http 是可以的

**Comment by monkeyWie** [comment]
添加了一个扩展点来满足这个需求，还是参考：https://github.com/monkeyWie/proxyee/blob/master/src/test/java/com/github/monkeywie/proxyee/AuthHttpProxyServer.java

**Comment by kickDick** [comment]
目前的确解决了 https 鉴权信息和 代理设置的问题  但是 http的请求 在设置代理后 会出现问题  无法访问 
这张为 http 请求 
![W5$EWPR(}3DUUJ0UE3$87PO](https://user-images.githubusercontent.com/25758570/128108263-ed5762f6-3412-4e18-be47-a9045f50b766.png)
这张为 https 请求 
![{AWJ(PBBW@TM_3L1$ED1P0L](https://user-images.githubusercontent.com/25758570/128108293-9595dc15-020c-4f3c-8c5a-b082ecd4a6d6.png)

**Comment by monkeyWie** [comment]
我测试了下没有问题呀，你检查下是不是二级代理服务器有问题啊

**Comment by kickDick** [comment]
是二级代理的问题 感谢

**Comment by monkeyWie** [comment]
没问题的话就把issue关了吧~

**Comment by kickDick** [comment]
感谢 感谢
