### ISSUE TITLE
io.netty.util.IllegalReferenceCountException: refCnt: 0

### ISSUE THREAD

**Issue by cosxec** [monkeyWie/proxyee#17]
作者好，首先感谢作者开源了proxyee，https和http都能支持代理！但是自己使用并测试了一段时间，发现了以下几个报错问题：
1、io.netty.util.IllegalReferenceCountException: refCnt: 0
2、io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: initialCapacity: -1130 (expectd: 0+)
有些网站请求会经常出现这个错误，导致部分页面获取响应内容丢失，但是刷新一遍后加载成功，困扰了很久了没找到解决方案。。。求作者科普。。。

**Comment by cosxec** [comment]
这是在响应中添加代码的截图
![rc](https://user-images.githubusercontent.com/35187618/36934672-4bbf23b4-1f28-11e8-8508-a4316796f1a2.png)

**Comment by monkeyWie** [comment]
你是扩展了什么功能呢

**Comment by cosxec** [comment]
文件上传不了，就是加了一个http解析的java类，遍历并处理了http的请求头和响应头， 在afterResponse方法中只做了一次ByteBuf复制，其他的没有修改。

**Comment by monkeyWie** [comment]
不用在源代码上改啊，直接写Intercept去处理，还有你哪个collectBuf方法里面的代码能贴出来吗

**Comment by cosxec** [comment]
private CompositeByteBuf byteBuf = Unpooled.compositeBuffer();
private int chunkNum;
public void collectBuf(ByteBuf buf) {
		this.byteBuf.addComponent(true, buf);
		chunkNum++;
	}
这是写的 收集buf的代码
能否具体告知是哪个Intercept类吗？

**Comment by cosxec** [comment]
我个人对netty也不是很了解，方便加下q吗

**Comment by monkeyWie** [comment]
加了
