### ISSUE TITLE
证书下载不能使用localhost

### ISSUE THREAD

**Issue by Enaium** [monkeyWie/proxyee#173]
serverConfig(config).start("localhost", 19808);

只能使用127.0.0.1

**Comment by monkeyWie** [comment]
确实有问题，我重新思考了下，不能用ip和port的方式来匹配是不是直接请求的代理服务器。
在代理服务器被http代理的时候，浏览器会传递一个`Proxy-Connection`头，通过这个头来区分来源是代理还是浏览器直接请求就可以搞定了。

**Comment by monkeyWie** [comment]
已修复：https://github.com/monkeyWie/proxyee/pull/174
