### ISSUE TITLE
Android7 不能用

### ISSUE THREAD

**Issue by Enaium** [monkeyWie/proxyee#175]
换了Android 11 正常

用的是README的例子

开启服务正常 拦截器不正常 下载证书那个拦截器也不行 也没报错

访问证书下载显示 net::ERR_EMPTY_RESPONSE

**Comment by monkeyWie** [comment]
用的最新版代码吗

**Comment by Enaium** [comment]
是

**Comment by monkeyWie** [comment]
我这里没有安卓7的手机，不好测试，你可以在[CertDownIntercept](https://github.com/monkeyWie/proxyee/blob/c96328d1950f343aa917014d56a300a005ae5b16/src/main/java/com/github/monkeywie/proxyee/intercept/common/CertDownIntercept.java#L53-L60)这个类上debug下看看吗

**Comment by Enaium** [comment]
好像是`ProtoUtil.getRequestProto(request)`这一步出的问题
https://pastebin.ubuntu.com/p/hhGNyj9fyk/

**Comment by monkeyWie** [comment]
@Enaium 应该的sdk版本太低了，不支持正则表达式group匹配

**Comment by Enaium** [comment]
group这个方法再api24有什么替代方法吗

**Comment by monkeyWie** [comment]
这个只能改代码了

**Comment by monkeyWie** [comment]
1.5.3 已修复
