### ISSUE TITLE
在FireFox浏览器代理加上CertDownIntercept拦截器需要登录

### ISSUE THREAD

**Issue by Enaium** [monkeyWie/proxyee#178]
会显示此网站需要登录才能访问 之后无论访问什么网站都会跳转证书下载页面
不加这个拦截器可以正常代理

**Comment by Enaium** [comment]
[![fhd2h6.png](https://z3.ax1x.com/2021/08/17/fhd2h6.png)](https://imgtu.com/i/fhd2h6)

**Comment by monkeyWie** [comment]
嗯 我下个火狐看看

**Comment by monkeyWie** [comment]
1.5.3已修复
