### ISSUE TITLE
Chaining proxies.

### ISSUE THREAD

**Issue by skanga** [monkeyWie/proxyee#190]
How can I configure proxee to itself talk to another upstream proxy?

Is it enough to just set the JVM flags http.proxyHost and http.proxyPort when starting your JVM on the command line?

**Comment by monkeyWie** [comment]
I think you might need this: https://github.com/monkeyWie/proxyee#pre-proxy-support

**Comment by skanga** [comment]
@monkeyWie - Thank you. This works.
