### ISSUE TITLE
Idiomatic way to add a health check endpoint 

### ISSUE THREAD

**Issue by er1c** [monkeyWie/proxyee#197]
If deploying an instance to AWS, or other cloud platforms, there should be a simple way to add a request/response for a healthcheck.

Example:

```
curl -v 127.0.0.1:9999/status/health
```

Would return a 200 response.

**Comment by monkeyWie** [comment]
This project is positioned as a library, the healthcheck should be implemented by bussiness, or I add a common interceptor like [CertDownIntercept.java](https://github.com/monkeyWie/proxyee/blob/master/src/main/java/com/github/monkeywie/proxyee/intercept/common/CertDownIntercept.java)

**Comment by er1c** [comment]
@monkeyWie I'm fine with that, thanks for the consideration.
