### ISSUE TITLE
unknown_ca

### ISSUE THREAD

**Issue by l454124613** [monkeyWie/proxyee#2]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca

这个问题如何处理？

**Comment by monkeyWie** [comment]
@l454124613 有全部异常日志吗

**Comment by l454124613** [comment]
类似这样的https ：  https://www.v2ex.com/t/116724  的网站 用谷歌代理 就会出现

**Comment by monkeyWie** [comment]
@l454124613 你把CA根证书导进浏览器了吗

**Comment by cainwise** [comment]
您好，你的ca.crt和ca_pub.der、ca_private.pem分别是怎么生成的
我自己采用了生成的证书老有问题
生成步骤：
1、openssl genrsa -out cakey.pem 2048
2、openssl req -new -key cakey.pem -out ca.csr
3、openssl x509 -req -days 365 -sha256 -extensions v3_ca -signkey cakey.pem -in ca.csr -out ca.cer
4、openssl pkcs8 -topk8 -nocrypt -inform PEM -outform DER -in cakey.pem -out ca_private.pem
5、openssl rsa -in cakey.pem -pubout -outform DER -out ca_pub.der
