### ISSUE TITLE
XP系统中，HttpProxyClientHandler中Channel提前关闭导致往浏览器传送数据中断

### ISSUE THREAD

**Issue by chq8191562** [monkeyWie/proxyee#207]
channelUnregistered方法中由于关闭了对浏览器的channel，
导致如果传送的文件比较大，在浏览器端接收不完整。（文件截断，原有5000行可能只接收2000行）

奇怪的是只是在XP系统中会出现这个问题，在win10系统中不会出这个问题。

现在临时的解决方案是注释掉channelUnregistered方法。
测试也没有发生内存溢出的情况。

不知道在这个方法中关闭对浏览器的channel是否合理？
或者需要等待全部写完再关闭？

**Comment by monkeyWie** [comment]
你试试前面加下`flush()`看看能行吗：
```java
clientChannel.flush();
clientChannel.close();
```

**Comment by chq8191562** [comment]
还是会截断，这里我研究的不深，flush()在nio里面是一个异步的操作吧？

访问的网页的connection属性是close，就是发送完数据就会立即关闭。
当前的close()调用的时点是服务器到代理已经传送完数据并断开，
但代理到浏览器还未传送完，
此时调用了close()，似乎就会导致到浏览器的数据截断。

看了一下channel的API，似乎没有监听channel已经空闲的方法，不知道这里可以如何处理。

**Comment by monkeyWie** [comment]
确实没必要关闭浏览器的channel，我改改吧

**Comment by monkeyWie** [comment]
已经release了，版本：1.6.3

**Comment by chq8191562** [comment]
OK，谢谢！
