### ISSUE TITLE
beforeconnect不生效

### ISSUE THREAD

**Issue by litht** [monkeyWie/proxyee#213]
更新host请求头时，使用的是旧的requestProto，没有用beforeconnect修改的requestProto
proxyee/handler/HttpProxyServerHandler 266行

**Comment by monkeyWie** [comment]
有找到是什么原因吗

**Comment by litht** [comment]
你重新设置请求头的时候没有用beforeconnect更新的，与目标主机连接用的getRequestproto，这个也没更新

**Comment by monkeyWie** [comment]
感谢指正，已修复：https://github.com/monkeyWie/proxyee/pull/214
