### ISSUE TITLE
beforeConnect只有第一个拦截器有效

### ISSUE THREAD

**Issue by litht** [monkeyWie/proxyee#216]
拦截器基类的beforeConnect方法没有写调用下一个拦截器的方法

**Comment by litht** [comment]
你自己定义的拦截器可以链式调用，证书下载拦截器你怎么处理，除非重写证书下载器

**Comment by monkeyWie** [comment]
感谢指正，已经加上了哈：https://github.com/monkeyWie/proxyee/pull/219
