### ISSUE TITLE
开启SSL解析，网络连接一直pending，关闭SSL解析则正常

### ISSUE THREAD

**Issue by cnsky2016** [monkeyWie/proxyee#224]
- 网站：https://www.douyin.com/discover
- proxyee版本：1.6.6
- jdk版本：1.8.0_333
- 是否使用自定义证书：是
- 调整cipher是否有效：否

**Comment by cnsky2016** [comment]
之前一段时间是可以的，最近一段时间才出现该问题

**Comment by monkeyWie** [comment]
有异常日志吗

**Comment by cnsky2016** [comment]
无异常日志

**Comment by cnsky2016** [comment]
看网站证书，好像最近更新过

**Comment by cnsky2016** [comment]
测试方式：启动proxyee，浏览器配置代理访问，浏览器开发者模式下，网络连接一直pending

**Comment by monkeyWie** [comment]
试了下确实不行，等我找找原因吧

**Comment by monkeyWie** [comment]
可以了，是响应里的header太大了，升级到1.6.7之后配置下max header size就行：
```
HttpProxyServerConfig config = new HttpProxyServerConfig();
config.setMaxHeaderSize(8192 * 2);
```

**Comment by cnsky2016** [comment]
确认可以了，感谢。大佬666

**Comment by cnsky2016** [comment]
问题解决，关闭
