### ISSUE TITLE
new HttpProxyServer().start(9999);不安装证书启动服务器代理无法正常工作（BUG）

### ISSUE THREAD

**Issue by king1982** [monkeyWie/proxyee#231]
原因为https://github.com/monkeyWie/proxyee/commit/493b74ef1f3af818c07ae78a887040b7304eeaed#diff-73a2c425ab6a713644306ff0b683716465231a7753d1f1e2670b0c509409e555的提交导致的。
解决办法：回滚上一版本

**Comment by king1982** [comment]
复现步骤：不需要证书，启动最简单的代理服务器，https均无法打开，http页面正常。经过排查，回滚git的版本为9/8号的即可解决

**Comment by monkeyWie** [comment]
感谢指出，已经修复：https://github.com/monkeyWie/proxyee/pull/232
