### ISSUE TITLE
根据规则选择二级代理是否启用 还有支持https吗？

### ISSUE THREAD

**Issue by hellomyheart** [monkeyWie/proxyee#238]
我想做的是和一些vpn客户端类似的， 
可以直接访问的请求， 本地代理直接返回，
不可以直接访问的请求， 走二级代理

可不可以访问，在访问之前做判断（通过请求域名判断）

这个可以实现吗，
如果是https请求，支持这种方式吗？

**Comment by monkeyWie** [comment]
支持的，参考这个pr：https://github.com/monkeyWie/proxyee/pull/121

**Comment by hellomyheart** [comment]
感谢
