### ISSUE TITLE
config.setHandleSsl(false); 设置不启用https的情况下如何进行https拦截？

### ISSUE THREAD

**Issue by xujimu** [monkeyWie/proxyee#253]
config.setHandleSsl(false); 设置后拦截器就不会进行拦截https流量，但是我现在有个需求，我需要拦截https，我只想拿到发起请求前的域名判断是否是在白名单 如果不在白名单则拒绝，如果在白名单就直接转发流量，并不需要篡改流量，这种需求能做到吗？

**Comment by monkeyWie** [comment]
客户端不装根证书的吗？如果装了在拦截器处理就行了啊

**Comment by xujimu** [comment]
> 看看这个行不行，参考：[AcceptHttpProxyServer.java](https://github.com/monkeyWie/proxyee/blob/master/src/test/java/com/github/monkeywie/proxyee/AcceptHttpProxyServer.java)

谢谢大佬 这个完美的解决了问题 给个建议哈 文档的话得更新下了 从文档里面很难知道还有AcceptHttpProxyServer 大部分人不会去了解源码 只会用 如果从文档中没有找到解决自己的需求的方案 可能就会找别的项目了

**Comment by monkeyWie** [comment]
文档有空我再补下吧
