### ISSUE TITLE
有没有办法根据request中header的标记决定请求是否走前置代理

### ISSUE THREAD

**Issue by xiaohutushen30** [monkeyWie/proxyee#259]
例如：                 
1.client request(header{"use_upstream": false})-------->proxyee-------->internet
2.client request(header{"use_upstream": true})-------->proxyee-------->前置代理--------->internet

**Comment by monkeyWie** [comment]
可以的，参考这个[pr](https://github.com/monkeyWie/proxyee/pull/121)
