### ISSUE TITLE
访问特定网页发生302重定向的次数过多的问题。

### ISSUE THREAD

**Issue by zhengchy** [monkeyWie/proxyee#27]
作者，你好，感谢你的proxyee代理程序，最近我在使用的过程中发现在访问http://wap.cmread.com/r/457427094/index.htm?cm=C0NA0001&vt=3
这个网址的时候，会发生302重定向次数过多的问题，但是使用其他代理服务器就没有这个问题。请帮忙定位一下，十分感谢。

**Comment by monkeyWie** [comment]
已修复。

**Comment by luyuanwan** [comment]
没看懂这个修复过程

**Comment by monkeyWie** [comment]
> 没看懂这个修复过程

讲真我也不太记得了😅
