### ISSUE TITLE
TCP 链接数量一致在增加

### ISSUE THREAD

**Issue by fellowming** [monkeyWie/proxyee#271]
TCP 链接数量一致在增加, 
经排查是有大量的链接没有关闭。
请问能通过什么配置 来设置自动关闭超时的链接吗?

**Comment by monkeyWie** [comment]
是客户端到代理服务的TCP连接吗

**Comment by fellowming** [comment]
是的
使用
`sudo ss -tuna | grep ESTAB ` 查看
都是到代理的链接
![image](https://github.com/monkeyWie/proxyee/assets/127200629/4e62bf71-3da2-4273-964b-cf67fb4e68b2)
443 为代理监听的端口

**Comment by monkeyWie** [comment]
加一个IdleStateHandler做存活检查应该就行了，你有兴趣来个PR吗

**Comment by fellowming** [comment]
OK,我搞个哈

**Comment by monkeyWie** [comment]
嗯嗯，对应的代码在这里：https://github.com/monkeyWie/proxyee/blob/9f41e9ffbb3f86d2b59704411b7efef2a6130931/src/main/java/com/github/monkeywie/proxyee/handler/HttpProxyInitializer.java#L27

**Comment by monkeyWie** [comment]
相关修复pr：https://github.com/monkeyWie/proxyee/pull/279
