### ISSUE TITLE
在阿里云申请了一个免费能信任的证书，替换了ca.crt和der，请问这个时候中间人做代理的时候，理论上会被信任吗

### ISSUE THREAD

**Issue by zzmgc4** [monkeyWie/proxyee#274]
![image](https://github.com/monkeyWie/proxyee/assets/27204937/b6a7cf01-d44c-4825-8e11-43c091642d9b)
我看代码里面做中间人都是动态生成每个被代理网站证书的

**Comment by monkeyWie** [comment]
不会的，这里的证书是根证书，阿里云申请的是根证书签发的证书

**Comment by zzmgc4** [comment]
我可以理解为只要开了中间人拦截，就一定会存在我截图上面证书不被信任的情况吗，然后用户再去主动点信任证书

**Comment by monkeyWie** [comment]
是的，所以需要用户手动安装根证书，你可以仔细阅读下说明文档：
https://github.com/monkeyWie/proxyee/blob/master/README_zh-CN.md#https-%E6%94%AF%E6%8C%81
