### ISSUE TITLE
大佬，支付宝APP抓不了包，报未知证书错误，但是其他APP可以，这是为啥呀 || Big Brother, the Alipay APP cannot capture the package, and reports an unknown certificate error, but other APPs can, why is this?

### ISSUE THREAD

**Issue by linhhhhhhhhh** [monkeyWie/proxyee#282]
![6b1c703a73f2f045b6a68d88113d5e6](https://github.com/monkeyWie/proxyee/assets/135700613/23ee5367-5a71-4c4d-ab10-b0275dfdb70d)
这是抓的头条的包
![08ccb7a8bc69bf8be68cf3f71f1bc13](https://github.com/monkeyWie/proxyee/assets/135700613/c4f21a37-27a3-4be7-aca0-0587a5982e87)
这是抓的支付宝的包

---
![6b1c703a73f2f045b6a68d88113d5e6](https://github.com/monkeyWie/proxyee/assets/135700613/23ee5367-5a71-4c4d-ab10-b0275dfdb70d)
This is the headline bag
![08ccb7a8bc69bf8be68cf3f71f1bc13](https://github.com/monkeyWie/proxyee/assets/135700613/c4f21a37-27a3-4be7-aca0-0587a5982e87)
This is the Alipay package

**Comment by monkeyWie** [comment]
重复问题：https://github.com/monkeyWie/proxyee/issues/133
