### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by SJTUwbl** [monkeyWie/proxyee#34]
浏览器访问一张图片，如何在代理服务器上进行拦截，将图片下载下来？谢谢！

**Comment by monkeyWie** [comment]
可以自定义一个拦截器，然后在`afterResponse`方法通过响应头里的`Content-Type`来判断是不是图片，是的话就下载下来。

**Comment by SJTUwbl** [comment]
实现了，多谢指导！
