### ISSUE TITLE
https 报错

### ISSUE THREAD

**Issue by Ease-on** [monkeyWie/proxyee#4]
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record:
ca.crt证书已经导入  “受信任的根证书颁发机构”了 @monkeyWie

**Comment by monkeyWie** [comment]
@Ease-on 是启动报错还是浏览器设置了http代理之后上网报错呢？

**Comment by Ease-on** [comment]
启动不报错，设置代理之后 打开https网页就报错 @monkeyWie

**Comment by Ease-on** [comment]
io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
警告: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: # @monkeyWie

**Comment by monkeyWie** [comment]
@Ease-on 浏览器打开网页有提示证书不受信任之类的吗？用的是什么浏览器啊

**Comment by Ease-on** [comment]
没有证书不受信任之类的提示  浏览器都试过了  ie，edge，chrome

**Comment by monkeyWie** [comment]
刚刚把代码clone下来测试了下，没有重新你的问题，你有改过代码吗
![image](https://user-images.githubusercontent.com/13160176/32204495-8d27221c-be24-11e7-91b7-d4d91cf31b78.png)

**Comment by Ease-on** [comment]
@monkeyWie  没有啊 只改了端口  其他的什么都没有改

**Comment by Ease-on** [comment]
@monkeyWie  咦chrome好像可以 IE,edge不行啊

**Comment by monkeyWie** [comment]
@Ease-on 嗯嗯，我刚刚在IE上试了下确实不行，开发的时候只在Chrome上测过，问题已经定位了，待会我解决了就push上来

**Comment by Ease-on** [comment]
@monkeyWie  ok 方便透露一下是什么问题吗

**Comment by monkeyWie** [comment]
@Ease-on IE和Chrome建立代理隧道的时候报文有点区别,我是用host头来取目标服务器端口号的，然而IE的host并没有带端口号。。
IE
```
CONNECT www.baidu.com:443 HTTP/1.0
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Proxy-Connection: Keep-Alive
Content-Length: 0
Host: www.baidu.com
Pragma: no-cache
```
Chrome
```
CONNECT www.baidu.com:443 HTTP/1.1
Host: www.baidu.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
```

**Comment by Ease-on** [comment]
哦哦 明白 @monkeyWie

**Comment by monkeyWie** [comment]
@Ease-on 已经修复了。

**Comment by Ease-on** [comment]
@monkeyWie ok 我已经pull了，试了一下，可以的，我刚开始学习netty，你能推荐一下书籍或者分享一下经验吗？

**Comment by monkeyWie** [comment]
@Ease-on 建议先把java NIO学好，再来用netty，这样可以通过看netty源码慢慢了解netty。
我入门书看的《netty权威指南》，在熟悉了socket编程之后其实就是去了解各种常用的应用层协议(http,https,websocket等等)。你可以尝试先用NIO实现一个简单的http服务器，然后再到netty里实现一个(不要用netty现成的)，没有对比就没有伤害，你会发现用netty框架开发非常的轻松愉快。
顺便分享下我看完《netty权威指南》后自己造的轮子，实现了简单的http服务器和websocket服务器。
[simple-websocket-server](https://github.com/monkeyWie/simple-websocket-server)

**Comment by Ease-on** [comment]
@monkeyWie ok，非常感谢!
