### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by 2133223** [monkeyWie/proxyee#43]
if ("CONNECT".equalsIgnoreCase(request.method().name())) {//建立代理握手
          status = 2;
          HttpResponse response = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1,
              HttpProxyServer.SUCCESS);
          ctx.writeAndFlush(response);
          ctx.channel().pipeline().remove("httpCodec");
          return;
        }
这段代码是什么作用啊？ 麻烦解释一下嘛，想了很久没想通，实在困扰。。谢谢了

**Comment by 2133223** [comment]
@monkeyWie

**Comment by monkeyWie** [comment]
这个是http代理的规范，可以看看我写的博客：https://segmentfault.com/a/1190000011810997
