### ISSUE TITLE
现在请求和响应的headers和content都是分开的，可以合在一起吗？

### ISSUE THREAD

**Issue by Ease-on** [monkeyWie/proxyee#5]
如题，可以将请求和响应的headers和content合在一起吗？网上说用httpobjectaggregator可以，但是我试了当请求是https的时候还是分开的 @monkeyWie

**Comment by monkeyWie** [comment]
@Ease-on 可以的，之前是用的HttpObjectAggregator，不过content内容太长的会导致内存异常，因为HttpObjectAggregator在响应体没读完之前会一直在内存里。如果不是下载或者上传大文件的话可以加上这个解码器

**Comment by Ease-on** [comment]
我现在reponse是合在一起了，但是request在https的情况下 还是不可以，headers和content还是分开的，而且还分包了 @monkeyWie

**Comment by monkeyWie** [comment]
你改了哪里呢？ @Ease-on

**Comment by Ease-on** [comment]
NettyHttpProxyServer里
ch.pipeline().addLast("httpCodec", new HttpServerCodec());
ch.pipeline().addLast("aggregator", new HttpObjectAggregator(1024*1024*64));

**Comment by monkeyWie** [comment]
https还要特殊处理下
```
if ("CONNECT".equalsIgnoreCase(request.method().name())) {//建立代理握手
                    status = 2;
                    HttpResponse response = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, NettyHttpProxyServer.SUCCESS);
                    ctx.writeAndFlush(response);
                    ctx.channel().pipeline().remove("httpCodec");
                    ctx.channel().pipeline().remove("aggregator");//这里加上
                    return;
                }

if (byteBuf.getByte(0) == 22) {//ssl握手
                isSSL = true;
                SslContext sslCtx = SslContextBuilder.forServer(NettyHttpProxyServer.serverPriKey, CertPool.getCert(this.host)).build();
                ctx.pipeline().addLast("aggregator", new HttpObjectAggregator(1024102464));//这里加上
                ctx.pipeline().addFirst("httpCodec", new HttpServerCodec());
                ctx.pipeline().addFirst("sslHandle", sslCtx.newHandler(ctx.alloc()));
                //重新过一遍pipeline，拿到解密后的的http报文
                ctx.pipeline().fireChannelRead(msg);
                return;
            }

 //HttpProxyInitializer.java
@Override
    protected void initChannel(Channel ch) throws Exception {
        if(isSSL){
            ch.pipeline().addLast(NettyHttpProxyServer.clientSslCtx.newHandler(ch.alloc()));
        }
        ch.pipeline().addLast("httpCodec",new HttpClientCodec());
        ch.pipeline().addLast("aggregator", new HttpObjectAggregator(1024102464));//这里加上
        ch.pipeline().addLast(new HttpProxyClientHandle(clientChannel));
    }

```

**Comment by Ease-on** [comment]
不不行啊，https的还是不可以，还是分开的;http没问题

**Comment by monkeyWie** [comment]
额，这里写错了
```
if (byteBuf.getByte(0) == 22) {//ssl握手
	isSSL = true;
	SslContext sslCtx = SslContextBuilder.forServer(NettyHttpProxyServer.serverPriKey, CertPool.getCert(this.host)).build();
	//这里加上HttpObjectAggregator 改成addFirst
	ctx.pipeline().addFirst("aggregator", new HttpObjectAggregator(1024102464));
	ctx.pipeline().addFirst("httpCodec", new HttpServerCodec());
	ctx.pipeline().addFirst("sslHandle", sslCtx.newHandler(ctx.alloc()));
	//重新过一遍pipeline，拿到解密后的的http报文
	ctx.pipeline().fireChannelRead(msg);
	return;
}
```

**Comment by Ease-on** [comment]
这样也不行啊  我就是这么写的啊

**Comment by monkeyWie** [comment]
我刚刚试了可以拿到FullHttpRequest啊。
![image](https://user-images.githubusercontent.com/13160176/32431989-ba57ba1c-c310-11e7-8375-916b9610f170.png)

**Comment by Ease-on** [comment]
是会进FullHttpRequest，你在if外打印日志，会执行多次的，
![tos9v o1ki o0vpc i0 gc](https://user-images.githubusercontent.com/33082990/32432294-00cfa652-c312-11e7-8aa9-7bb7ab84bb9b.png)

**Comment by monkeyWie** [comment]
看样子是ssl握手后的解码器处理有问题，你把 if (byteBuf.getByte(0) == 22) {//ssl握手 里的代码贴下出来看看

**Comment by Ease-on** [comment]
和你的一样啊
![8q fgemtgaioon2 ovo b](https://user-images.githubusercontent.com/33082990/32432808-da469f8e-c313-11e7-9ae1-c388a2a7782c.png)

**Comment by monkeyWie** [comment]
httpCodec和aggregator顺序弄反了。
正确的Codec顺序应该是：sslHandle->httpCodec->aggregator->serverHandle

**Comment by Ease-on** [comment]
不行，不行的 

![Uploading D)ERS{~`{J%Z}S1`%DE{WUT.png…]()

**Comment by monkeyWie** [comment]
图片挂了！最好是把代码和控制台输出都截下来

**Comment by Ease-on** [comment]
![bm 9 g iuap68dzwyum 7qn](https://user-images.githubusercontent.com/33082990/32435753-d5622868-c31c-11e7-9f49-1e66d10571ff.png)
![uzq4z6 lsp s q80xgn8bm](https://user-images.githubusercontent.com/33082990/32435766-e03e1878-c31c-11e7-80c1-4c3b16d12b10.png)

**Comment by monkeyWie** [comment]
这样写
```
ctx.pipeline().addFirst("aggregator", new HttpObjectAggregator(1024102464));
ctx.pipeline().addFirst("httpCodec", new HttpServerCodec());
ctx.pipeline().addFirst("sslHandle", sslCtx.newHandler(ctx.alloc()));
```
注意这里是addFirst()，而NettyHttpProxyServer里是addLast()所以顺序要反过来

**Comment by Ease-on** [comment]
现在是可以的，但是现在是握手一次请求，传递参数一次请求， 现在一个http请求实际上是发了3次才完成；这个可以合成一个完成吗？

**Comment by monkeyWie** [comment]
这个不行的，https代理建立代理隧道要一次握手，然后ssl建立也要握手，是不能少的。

**Comment by Ease-on** [comment]
现在是这里判断是不是https的
![s tb q046lqp fjfqkw7 r](https://user-images.githubusercontent.com/33082990/32484435-c40406b8-c3da-11e7-94a9-a7022ddfc6bb.png)
是Https的时候HttpRequest.uri里是没有https的  只有uri（host+port），那还有其他方法能够拿到https吗,

**Comment by monkeyWie** [comment]
只有在ssl握手的时候才能知道是不是https的，因为ssl之后实际上只是传输普通的加密http报文而已。
