### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by louyu65** [monkeyWie/proxyee#54]

**Comment by hanjiangxuehua** [comment]
我也遇到了这个问题，转发到目的服务器时发生connection timeout 和connection refuse，服务端会直接报错，并没有返回任何信息到客户端，客户端（浏览器）一直在等待服务器信息

**Comment by monkeyWie** [comment]
有没有具体的复现步骤方便我重现下呢？

**Comment by hanjiangxuehua** [comment]
不好意思，我这个问题已经解决了，是由于我转发请求时把httpcontent丢弃了，导致一直等待timeout问题

**Comment by monkeyWie** [comment]
ok，那我关了这个issue
