### ISSUE TITLE
如何启动和使用?

### ISSUE THREAD

**Issue by hrj5032188** [monkeyWie/proxyee#58]
这个如何启动?
我直接run NormalHttpProxyServer 的main方法 没有任何动静
我在下面输出了一句话 然后拿手机访问了ip:9999

控制台输出: 
![image](https://user-images.githubusercontent.com/28888068/58531392-b9392e80-8214-11e9-9e8b-2714443bfc03.png)

**Comment by monkeyWie** [comment]
启动了之后设置HTTP代理再访问网页才行

**Comment by hrj5032188** [comment]
是用tomcat启动还是用test启动?

**Comment by monkeyWie** [comment]
浏览器设置HTTP代理然后访问网站啊

**Comment by lan0813** [comment]
请问这个java.io.IOException: 远程主机强迫关闭了一个现有的连接。
怎么解决？

**Comment by monkeyWie** [comment]
参考 #62
