### ISSUE TITLE
警告: An exception 'java.lang.Exception: java.io.IOException: 远程主机强迫关闭了一个现有的连接。' 

### ISSUE THREAD

**Issue by lan0813** [monkeyWie/proxyee#62]
怎么解决。。
打印的时候上面两条自己添加的Pirnt都无法显示，只有最后一条可以显示

**Comment by lan0813** [comment]
![QQ图片20190825175216](https://user-images.githubusercontent.com/41324435/63648342-1b94c300-c761-11e9-9672-cb52436729c0.png)

**Comment by monkeyWie** [comment]
这个没关系，你可以自定义`HttpProxyExceptionHandle`处理异常
