### ISSUE TITLE
您好，请务必帮我解决下，救命！

### ISSUE THREAD

**Issue by wayddmldbzz** [monkeyWie/proxyee#69]
1.假设我现在把config.setHandleSsl(false);设置为false后，我看了下代码应该所有请求都走隧道代理，无论什么https请求都能正常访问，这时候我能否把一个https请求的HOST改一下，比如aaa.test.ooo.com改成bbb.test.ooo.com，前三级域名是一样的，而且我能拿到这个域名的证书和私钥，如果需要配置怎么配置，拜托看一下，救命！
2.正常配置好代理后大部分手机是能明文抓包的，但是发现有部分安卓机在访问app内部的H5页面的时候会提示
![image](https://user-images.githubusercontent.com/28469498/68033139-1708ff80-fcfa-11e9-9a17-65d22bca003e.png)
这种情况咋办啊，救命的事，谢谢哥们受累看一下！

**Comment by monkeyWie** [comment]
@wayddmldbzz 
1. 如果你不需要明文抓包的话是可以做到的，不过得改下代码去支持hook握手
2. 这个问题暂时解决不了，高版本安卓有时候对手动安装的根证书是不信任

**Comment by wayddmldbzz** [comment]
> @wayddmldbzz
> 
> 1. 如果你不需要明文抓包的话是可以做到的，不过得改下代码去支持hook握手
> 2. 这个问题暂时解决不了，高版本安卓有时候对手动安装的根证书是不信任
