### ISSUE TITLE
救命贴续，那个点错了给关了！

### ISSUE THREAD

**Issue by wayddmldbzz** [monkeyWie/proxyee#70]
第一个能实现就行了，还得麻烦哥们给我写个代码段，在哪个类下面改，对这个ssl认证知识和netty的逻辑不太熟不知道咋改，辛苦了！

**Comment by wayddmldbzz** [comment]
@monkeyWie 求指导啊，实在不知道在哪里改!

**Comment by monkeyWie** [comment]
我试了下发现没这么好实现啊，还是得配合证书一起

**Comment by wayddmldbzz** [comment]
这个要改的证书和私钥我有，怎么改，哥们指导一下，辛苦看看啦，救命的事！

**Comment by monkeyWie** [comment]
@wayddmldbzz 这个需求太奇怪了吧，为什么不安装根证书去做呢

**Comment by monkeyWie** [comment]
还有个问题，目标服务器如果会检测 host 请求头那么也实现不了

**Comment by wayddmldbzz** [comment]
这个没事，公司内部系统不回校验请求头，而且是纯内网调用。

**Comment by wayddmldbzz** [comment]
@monkeyWie 主要还是安装根证书去做，但是有的高版本手机会不行，所以为了不阻塞使用，还得支持这个，否则肯定会被diss

**Comment by monkeyWie** [comment]
@wayddmldbzz 有个问题，比如你现在是 aaa.test.ooo.com 改成 bbb.test.ooo.com，你的bbb.test.ooo.com证书中是否支持aaa.test.ooo.com域名？

**Comment by wayddmldbzz** [comment]
支持，aaa.test.ooo.com和bbb.test.ooo.com证书是一个

**Comment by monkeyWie** [comment]
加了个拦截器，你试试
```java
  new HttpProxyServer()
                .tunnelIntercept(requestProto -> {
                    if(requestProto.getHost().equals("aaa.test.ooo.com")){
                        requestProto.setHost("bbb.test.ooo.com");
                    }
                })
                .start(9999);
```

**Comment by wayddmldbzz** [comment]
万分感谢，我现在试，这个拦截器用倒入证书吗？

**Comment by monkeyWie** [comment]
不需要安装证书

**Comment by wayddmldbzz** [comment]
哥们虽然HOST变更了，但是调用的还是改之前的服务。

**Comment by monkeyWie** [comment]
额 你们是用的nginx做的反向代理吗？

**Comment by wayddmldbzz** [comment]
目标服务器nginx正向代理
![image](https://user-images.githubusercontent.com/28469498/68109323-36d03b80-ff25-11e9-83ce-cab53668eccb.png)
到断点那，已经替换了，下面进隧道拦截器数据状态正常吗，channel里面那个R:127.0.0.1:58068是我本地postman也就是客户端，您看看这数据对吗？

**Comment by monkeyWie** [comment]
数据没问题，应该还是nginx那边的问题，因为nginx会根据host请求头路由到对应的服务，虽然连接的是`bbb.test.ooo.com`但是nginx接收到的host请求头还是`aaa.test.ooo.com`

**Comment by wayddmldbzz** [comment]
那这个拦截器能否修改请求头呢？

**Comment by monkeyWie** [comment]
改不了的，没有安装根证书不行

**Comment by wayddmldbzz** [comment]
就是客户端必须安装证书？

**Comment by monkeyWie** [comment]
是啊，你这个场景实现条件太苛刻了

**Comment by wayddmldbzz** [comment]
nginx能不能改成用链接地址转发，如果能的话我推动改nginx在配合你改的就行了吧

**Comment by wayddmldbzz** [comment]
哥们有转机了，我刚了解了一下，不明文也可以修改请求头，https只加密请求体。

**Comment by monkeyWie** [comment]
@wayddmldbzz https所有报文都加密的

**Comment by wayddmldbzz** [comment]
@monkeyWie 误导了，改了也不行，最后还是我用了你的新改的转发，直接转到我自己的nginx，我自己的nginx配证书设置请求头，再转到目标nginx解决的。总之谢谢哥们救命之恩。。。万分感谢！

**Comment by monkeyWie** [comment]
好了就行😃

**Comment by liming1985** [comment]
tunnelIntercept  这个拦截器可以处理https的吗

**Comment by wayddmldbzz** [comment]
可以，但是只能改目标地址
