### ISSUE TITLE
 手机上不用WIFI 有办法设置HTTP代理吗？

### ISSUE THREAD

**Issue by peachyy** [monkeyWie/proxyee#73]
手机上不用WIFI 有办法设置代理吗？
 有什么软件直接可以使用吗 不用重新开发一个壳的这种。或者有其他方法吗

**Comment by monkeyWie** [comment]
手机上可以用vpn这种机制，不用设置HTTP代理

**Comment by zerorooot** [comment]
硬要设置也是可以的，不过要公网ip或者内网穿透
不同手机操作不同，我的是这样的
打开设置->WLAN和互联网->sim卡和移动网络->sim卡1->接入点名称(apn)->设置新的接入点->百度找参数，其中代理填你的公网ip，端口就是你设置的端口
