### ISSUE TITLE
如何获取POST请求参数

### ISSUE THREAD

**Issue by william-abel** [monkeyWie/proxyee#80]
如何获取POST请求参数，例如下面图片中的Form Data的数据![image](https://user-images.githubusercontent.com/45378809/72131032-15bd1880-33b6-11ea-9d0f-493e1edecd0a.png)

**Comment by monkeyWie** [comment]
从请求体里面拿就好了，参考 https://github.com/monkeyWie/proxyee/blob/master/src/test/java/com/github/monkeywie/proxyee/InterceptFullRequestProxyServer.java

**Comment by william-abel** [comment]
> 从请求体里面拿就好了，参考https://github.com/monkeyWie/proxyee/blob/master/src/test/java/com/github/monkeywie/proxyee/InterceptFullRequestProxyServer.java

Debug 进入不了handelRequest 在哪个方法里拿参数?

**Comment by monkeyWie** [comment]
你可能需要重写`match`方法，匹配到的请求才会被拦截
![image](https://user-images.githubusercontent.com/13160176/72201582-a0724600-3490-11ea-9b86-01d7feceaee3.png)

**Comment by william-abel** [comment]
> 你可能需要重写`match`方法，匹配到的请求才会被拦截
> ![image](https://user-images.githubusercontent.com/13160176/72201582-a0724600-3490-11ea-9b86-01d7feceaee3.png)

谢谢 已经获取到参数了 还有一个小问题 打包成jar java -jar 运行一直是 jar中没有主清单属性

**Comment by monkeyWie** [comment]
你怎么打的jar包啊，要打成可运行的jar才行

**Comment by william-abel** [comment]
> 你怎么打的jar包啊，要打成可运行的jar才行

通过maven 和 Idea build Artifacts 打包 都无法运行 未修改项目代码

**Comment by monkeyWie** [comment]
这个项目本身就不是可运行jar包啊，要打包的话需要修改`pom.xml`文件，示例
```xml
 <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <!-- 这里填要运行的类名 -->
                            <mainClass>lee.study.xxx.xxx</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>assembly</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
```

**Comment by william-abel** [comment]
> 这个项目本身就不是可运行jar包啊，要打包的话需要修改`pom.xml`文件，示例
> 
> ```
>  <build>
>         <plugins>
>             <plugin>
>                 <artifactId>maven-assembly-plugin</artifactId>
>                 <configuration>
>                     <appendAssemblyId>false</appendAssemblyId>
>                     <descriptorRefs>
>                         <descriptorRef>jar-with-dependencies</descriptorRef>
>                     </descriptorRefs>
>                     <archive>
>                         <manifest>
>                             
>                             <mainClass>lee.study.xxx.xxx</mainClass>
>                         </manifest>
>                     </archive>
>                 </configuration>
>                 <executions>
>                     <execution>
>                         <id>make-assembly</id>
>                         <phase>package</phase>
>                         <goals>
>                             <goal>assembly</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-compiler-plugin</artifactId>
>             </plugin>
>         </plugins>
>     </build>
> ```
你有其他联系方式吗 有些问题请教你

**Comment by william-abel** [comment]
httpResponse.content().writeBytes 修改数据 缓存中的长度 和 要修改进去的数据长度不一致 导致原先的数据会有预留 由于都是JSON 所以格式就会出错

**Comment by monkeyWie** [comment]
加我微信吧 liwei-8466
