### ISSUE TITLE
代理服务端可以配置user和pwd吗？

### ISSUE THREAD

**Issue by 772451348** [monkeyWie/proxyee#89]
ProxyConfig中有配置user和pwd，但是服务端没有相应配置，请问应该怎么处理

**Comment by monkeyWie** [comment]
目前还不支持哦

**Comment by smichea** [comment]
Do you plan to implement it ?
or could you give some pointer so we can implement it.
 It is basically adding some proxy-authentication header no ?

**Comment by monkeyWie** [comment]
@smichea I plan to do it, but recently is no time, I may have to implement it next week.

**Comment by monkeyWie** [comment]
@772451348 @smichea
Already support, see https://github.com/monkeyWie/proxyee/pull/129.
