### ISSUE TITLE
EN support

### ISSUE THREAD

**Issue by BogdanLivadariu** [monkeyWie/proxyee#99]
hi
would it be possible to have some [english ](https://translate.google.ro/?hl=ro#view=home&op=translate&sl=auto&tl=zh-CN&text=hi%0Awould%20it%20be%20possible%20to%20have%20some%20english%20support%20for%20this%20project%20%3F%0A%0AThanks)support for this project ?

Thanks

**Comment by monkeyWie** [comment]
sure, I will do it.

**Comment by monkeyWie** [comment]
@BogdanLivadariu English is now supported, but my English is not very good, so please report back if you have any questions.

**Comment by BogdanLivadariu** [comment]
thanks @monkeyWie
